services:
  # postgres database
  postgres:
    image: postgres:14.15-alpine3.21
    container_name: $APP_NAME-postgres
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_USER: $DATABASE_USER
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  # postgres admin interface
  postgres_admin:
    image: dpage/pgadmin4:2024-10-19-2
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
      PGADMIN_CONFIG_ALLOW_SPECIAL_EMAIL_DOMAINS: "['local']"
    ports:
      - 5433:80 # admin ui
